# Advanced Topics in NumPy Operations

**Broadcasting**

In [2]:
#Basic Broadcast Example
import numpy as np

# Create a 2x3 matrix
a = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 1x3 row vector
b = np.array([1, 2, 3])

# Broadcast and add
c = a + b
print(c)

[[2 4 6]
 [5 7 9]]


**Linear Algebra**

In [3]:
#Matrix Multiplication:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.dot(A, B)
print(C)

[[19 22]
 [43 50]]


In [4]:
#Determinant:
det_A = np.linalg.det(A)
print(det_A)

-2.0000000000000004


In [5]:
#Eigenvalues and Eigenvectors:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [6]:
#Inverse of Matrix:
inv_A = np.linalg.inv(A)
print(inv_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


# Advanced Indexing and Slicing

In [7]:
#Boolean Indexing
x = np.array([1, 2, 3, 4, 5])
print(x[x > 2])

[3 4 5]


In [8]:
#Fancy Indexing
y = np.array([10, 20, 30, 40, 50])
indices = [1, 3, 4]
print(y[indices])

[20 40 50]


In [9]:
#combining Indexing Tachniques
z = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(z[1:, [0, 2]])

[[4 6]
 [7 9]]


# Performance Optimization

In [10]:
#Vectorization
# Loop-based
a = np.arange(1000000)
b = np.arange(1000000)
c = np.zeros(1000000)
for i in range(1000000):
    c[i] = a[i] + b[i]

# Vectorized
d = a + b

In [11]:
#Memory Layout
# C-order (row-major)
a_c = np.array([[1, 2, 3], [4, 5, 6]], order='C')

# F-order (column-major)
a_f = np.array([[1, 2, 3], [4, 5, 6]], order='F')

print(a_c.flags)
print(a_f.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [12]:
#Using In-Place Operations
a = np.array([1, 2, 3, 4, 5])
a += 1
print(a)

[2 3 4 5 6]


# Random Number Generation

**Basic Random Number Generation** 

In [13]:
random_numbers = np.random.rand(5)
print(random_numbers)

[0.22831539 0.44509537 0.02681606 0.98523632 0.64659327]


**Creating Random Arrays**

In [14]:
random_array = np.random.randint(0, 10, (3, 3))
print(random_array)

[[2 0 6]
 [6 0 4]
 [2 6 1]]


**Setting the Random Seed**

In [15]:
np.random.seed(42)
reproducible_random = np.random.rand(3)
print(reproducible_random)

[0.37454012 0.95071431 0.73199394]


Mastery of these topics will enable you to handle complex data manipulation tasks and optimize your computational workflows effectively