# Linear Algebra Operations

In [1]:
import numpy as np

In [3]:
#Creating Matrics
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

**Basic Operations**

In [5]:
#Matrix Addition
C = A + B
print(C)

[[ 6  8]
 [10 12]]


In [6]:
#Matrix Subtraction
D = A - B
print(D)

[[-4 -4]
 [-4 -4]]


In [7]:
#Matrix Multiplication
E = np.dot(A, B)
print(E)

# Alternatively
F = A @ B
print(F)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [8]:
#Transpose of a Matrix
G = A.T
print(G)

[[1 3]
 [2 4]]


In [9]:
#Determination of a Matrix
H = np.linalg.det(A)
print(H)

-2.0000000000000004


In [10]:
#Inverse of a Matrix
I = np.linalg.inv(A)
print(I)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [11]:
#Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [12]:
#Singular Value Decomposition(SVD)
U, S, V = np.linalg.svd(A)
print("U matrix:", U)
print("Singular values:", S)
print("V matrix:", V)

U matrix: [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular values: [5.4649857  0.36596619]
V matrix: [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [13]:
#Solving Linear Equations
b = np.array([1, 2])
x = np.linalg.solve(A, b)
print(x)

[0.  0.5]


In [14]:
#Norms of Vectors and Matrices
# Frobenius norm
fro_norm = np.linalg.norm(A)
print(fro_norm)

# L2 norm of a vector
v = np.array([3, 4])
l2_norm = np.linalg.norm(v)
print(l2_norm)

5.477225575051661
5.0


Mastering these operations is crucial for leveraging the full power of NumPy in scientific computing and data analysis.