# BASIC OPERATIONS

In [2]:
import numpy as np

**Creating Arrays**

In [3]:
#From a list
a =np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
#From a nested list(to create a matrix)
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


**Using built-in functions:**

In [5]:
#Zeros array:
c =np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
#Ones array:
d = np.ones((2,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
#Empty array(uninitialized):
e = np.empty((2,2))
print(e)

[[2.12199579e-314 3.16251293e+180]
 [4.28848981e-321 1.54693493e-311]]


In [9]:
#array with a range of values:
f = np.arange(0,10,2)
print(f)

[0 2 4 6 8]


In [10]:
#array with evenly spaced values:
g = np.linspace(0,1,5)
print(g)

[0.   0.25 0.5  0.75 1.  ]


**Basic Array Operations**

In [12]:
#Element-wise addition:
h = np.array([1,2,3])
i = np.array([4,5,6])
print(h+i)

[5 7 9]


In [13]:
print(h*i)

[ 4 10 18]


In [14]:
#Matrix multiplication:
j = np.array([[1,2], [3,4]])
k = np.array([[5,6], [7,8]])
print(np.dot(j,k))

[[19 22]
 [43 50]]


**Array Indexing and Slicing**

In [16]:
#Accessing an element:
l = np.array([1,2,3,4,5])
print(l[2])

3


In [17]:
#slicing an array:
print(l[1:4])

[2 3 4]


In [18]:
#Indexing a 2D array:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(m[1,2])

6


In [19]:
#Reshaping Arrays
n = np.array([[1,2,3], [4,5,6]])
print(n.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]
